[package]
name = "qoreutils-chmod"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "qchmod"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.75"
clap = { version = "4.2.0" }
tempfile = "3.8.0"
