[package]
name = "qoreutils-base64"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "qbase64"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
clap = "4.1.11"
